const actionTypes = {

    //auth
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAILED',





    //music
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    PLAY: 'PLAY',
    SET_RECENT:'SET_RECENT',
    SET_COMMENT_SONG_ID:'SET_COMMENT_SONG_ID',


    // actions
    SET_IS_OPEN_CREPLAYLIST_MODAL: 'SET_IS_OPEN_CREPLAYLIST_MODAL',
    SET_IS_OPEN_COMMENT_MODAL: 'SET_IS_OPEN_COMMENT_MODAL',
    CREATE_PLAYLIST:'CREATE_PLAYLIST',
    //use in playlist detail
    CREATE_ALL_PLAYLIST: 'CREATE_ALL_PLAYLIST',
    //user
    SET_USERNAME: 'SET_USERNAME',


    //favorite
    SET_FAVORITE:'SET_FAVORITE',
    REMOVE_FAVORITE:'REMOVE_FAVORITE'


};
export {actionTypes};
